#
## DEFINITION OF THE BALL CHALLENGE ARENA
#
 
use_utm_origin: true
utm_origin_units: 0 # 0 - UTM, 1 - Latitude Longitude
utm_origin_lat: 0
utm_origin_lon: 0
utm_origin_x: 465710.76
utm_origin_y: 5249465.43

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  frame_name: "gps_origin"

  polygon_obstacles:
    # loaded as a vector of matrices
    # each matrix has polygon vertices in columns
    # [[M1], [M2]]
    enabled: false
    data: [1, 10, 10, 1,    5, 8, 5,
           1, 1, 10, 10,    5, 5, 8,]
    rows: 2 # each matrix has two rows
    cols: [4, 3] # nums of cols of each matrix

  point_obstacles:
    # loaded as a vector of matrices
    # x, y, radius
    enabled: true
    data: [-5.0, -5.0, 5, 2.5] # 1st point
    rows: 1 # each matrix has a single row
    cols: [4] # nums of cols of each matrix

  # convex polygon CCW
  # race track
  safety_area: [
    23.23, -10.01,
    23.75, 21.17,
    20.26, 23.95,
    -22.09, 18.65,
    -23.83, 13.81,
    -23.83, -13.31,
    -19.77, -18.60,
    19.68, -15.18]

  max_height: 30.0
  min_height: 1.0


arena_ang_diff: 1.554235
arena_center: [-0.74, 2.06]
arena_corners: [
  23.15, -14.88, # K
  23.80, 24.39, # L
  -23.83, 18.43, # M
  -23.83, -18.95] # N

takeoff_center: [0.00, 0.00]
takeoff_zone: [
  -0.98, 1.52,
  -1.02, -1.48,
  0.98, -1.52,
  1.02, 1.48]

arena_type: 'wall_arena'

uav_wall_center: [-17.00, 2.00]
uav_wall_zone: [
  -17.46, 4.51,
  -17.54, -0.49,
  -16.54, -0.51,
  -16.46, 4.49]

uav_brick_center: [-10.00, -12.00]
uav_brick_zone: [
  -10.46, -9.49,
  -10.54, -14.49,
  -9.54, -14.51,
  -9.46, -9.51]

ugv_wall_center: [7.00, 7.00]
ugv_wall_zone: [
  6.54, 9.51,
  6.46, 4.51,
  7.46, 4.49,
  7.54, 9.49]

ugv_brick_center: [10.00, -5.00]
ugv_brick_zone: [
  9.54, -2.49,
  9.46, -7.49,
  10.46, -7.51,
  10.54, -2.51]
