#
## DEFINITION OF THE ARENA
#

utm_origin_units: 1 # 0 - UTM, 1 - Latitude Longitude
# !!! BEWARE !!!: the lat&lon and UTM coordinates below might be wrong
# !!! do NOT just switch utm_origin_units from 0<->1, the other form
# !!! might not be updated or even set correctly in the first place.
utm_origin_x: 0
utm_origin_y: 0
utm_origin_lat: 47.397743
utm_origin_lon: 8.545594

init_gps_garmin_origin_local: true # origin of gps_garmin_origin will be in the position of UAV at odometry launch
init_gps_offset_x: 0.0 # initial position of UAV relative to gps_garmin_origin when init_gps_garmin_origin_local is enabled
init_gps_offset_y: 0.0 # initial position of UAV relative to gps_garmin_origin when init_gps_garmin_origin_local is enabled

safety_area:

  use_safety_area: false

  frame_name: "slam_origin"

  max_height:  100.0
  min_height: -100.0
